version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres-container
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    volumes:
      - db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: pm-service
    environment:
      DB_HOST: localhost
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: database
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  db:
