version: '3.8'

services:
  app:
    image: pm-service
    container_name: pm-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - PORT=8080

  postgres:
    image: postgres:latest
    restart: always
    container_name: db_postgres
    environment:
      - POSTGRES_USER: admin
      - POSTGRES_PASSWORD: password
      - POSTGRES_DB: database
      - POSTGRES_HOST: localhost
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
